[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "bipedal_locomotion_isaaclab"
author = "Xiong Hongwei, Wang Bobin"
maintainer = "Xiong Hongwei, Wang Bobin"
description="Locomotion tasks for bipedal robots in IsaacLab"
repository = "https://github.com/81578823/bipedal_locomotion_isaaclab.git"
keywords = ["isaaclab", "bipedal", "locomotion", "pointfoot"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "bipedal_locomotion"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
